"""add charger availability table

Revision ID: 24bbf48e6a75
Revises: d6a51da8929b
Create Date: 2026-08-24 00:14:07.151418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bbf48e6a75'
down_revision: Union[str, Sequence[str], None] = 'd6a51da8929b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charger_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('charger_port_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_local_time', sa.Time(), nullable=False),
    sa.Column('end_local_time', sa.Time(), nullable=False),
    sa.Column('is_unavailable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['charger_port_id'], ['app.charger_ports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charger_availability', schema='app')
    # ### end Alembic commands ###
