"""add business constraints

Revision ID: 85f1f614b2bc
Revises: 30164f5d3fc2
Create Date: 2026-08-24 01:51:04.405416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f1f614b2bc'
down_revision: Union[str, Sequence[str], None] = '30164f5d3fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_business_deleted_at_after_created_at', 'businesses', 'deleted_at IS NULL OR deleted_at >= created_at', schema='app')
    op.create_check_constraint('ck_business_verification_status', 'businesses', "verification_status IN ('unverified', 'pending', 'verified', 'rejected')", schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_business_verification_status', 'businesses', schema='app', type_='check')
    op.drop_constraint('ck_business_deleted_at_after_created_at', 'businesses', schema='app', type_='check')
    # ### end Alembic commands ###
