"""add vehicle constraints

Revision ID: cca1eddf0515
Revises: 8ac87f0bdedc
Create Date: 2026-08-24 02:23:56.834105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca1eddf0515'
down_revision: Union[str, Sequence[str], None] = '8ac87f0bdedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_vehicles_model_year', 'vehicles', 'model_year IS NULL OR model_year BETWEEN 1886 AND 2100', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_vehicles_model_year', 'vehicles', schema='app', type_='check')
    # ### end Alembic commands ###
