"""add charger ports table

Revision ID: d6a51da8929b
Revises: ccf402c26475
Create Date: 2026-08-24 00:09:36.330442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a51da8929b'
down_revision: Union[str, Sequence[str], None] = 'ccf402c26475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charger_ports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('charger_id', sa.UUID(), nullable=False),
    sa.Column('connector_type_id', sa.Integer(), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('max_power_kw', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['charger_id'], ['app.chargers.id'], ),
    sa.ForeignKeyConstraint(['connector_type_id'], ['app.connector_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charger_ports', schema='app')
    # ### end Alembic commands ###
