"""add amenity constraints

Revision ID: 0cda3d51dc6b
Revises: 85f1f614b2bc
Create Date: 2026-08-24 01:52:52.312627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cda3d51dc6b'
down_revision: Union[str, Sequence[str], None] = '85f1f614b2bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_amenity_code_not_blank', 'amenities', 'length(trim(code)) > 0', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_amenity_code_not_blank', 'amenities', schema='app', type_='check')
    # ### end Alembic commands ###
