"""add charger search event constraints

Revision ID: 27e2cea710ae
Revises: 44009d3aaeb4
Create Date: 2026-08-24 02:34:15.715836

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "27e2cea710ae"
down_revision: str | Sequence[str] | None = "44009d3aaeb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
