"""add business hours constraints

Revision ID: 30164f5d3fc2
Revises: dcd4c94fc051
Create Date: 2026-08-24 01:48:48.819520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30164f5d3fc2'
down_revision: Union[str, Sequence[str], None] = 'dcd4c94fc051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_business_hours_day_of_week', 'business_hours', 'day_of_week BETWEEN 0 AND 6', schema='app')
    op.create_check_constraint('ck_business_hours_effective_date_order', 'business_hours', 'effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from', schema='app')
    op.create_check_constraint('ck_business_hours_time_order', 'business_hours', 'close_local_time > open_local_time', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_business_hours_time_order', 'business_hours', schema='app', type_='check')
    op.drop_constraint('ck_business_hours_effective_date_order', 'business_hours', schema='app', type_='check')
    op.drop_constraint('ck_business_hours_day_of_week', 'business_hours', schema='app', type_='check')
    # ### end Alembic commands ###
