"""add charger search event constraints

Revision ID: 44009d3aaeb4
Revises: cca1eddf0515
Create Date: 2026-08-24 02:28:46.824803

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44009d3aaeb4"
down_revision: str | Sequence[str] | None = "cca1eddf0515"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_charger_search_event_chargers_found_nonnegative",
        "charger_search_events",
        "chargers_found >= 0",
        schema="app",
    )
    op.create_check_constraint(
        "ck_charger_search_event_power_nonnegative",
        "charger_search_events",
        "requested_power_kw IS NULL OR requested_power_kw >= 0",
        schema="app",
    )
    op.create_check_constraint(
        "ck_charger_search_event_radius_nonnegative",
        "charger_search_events",
        "search_radius_km IS NULL OR search_radius_km >= 0",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_charger_search_event_radius_nonnegative",
        "charger_search_events",
        schema="app",
        type_="check",
    )
    op.drop_constraint(
        "ck_charger_search_event_power_nonnegative",
        "charger_search_events",
        schema="app",
        type_="check",
    )
    op.drop_constraint(
        "ck_charger_search_event_chargers_found_nonnegative",
        "charger_search_events",
        schema="app",
        type_="check",
    )
    # ### end Alembic commands ###
