"""add user constraints

Revision ID: 8ac87f0bdedc
Revises: fd6da38b3154
Create Date: 2026-08-24 02:05:50.501289

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ac87f0bdedc"
down_revision: str | Sequence[str] | None = "fd6da38b3154"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_users_email_not_blank", "users", "email IS NULL OR btrim(email) <> ''", schema="app"
    )
    op.create_check_constraint(
        "ck_users_name_not_blank", "users", "btrim(name) <> ''", schema="app"
    )
    op.create_check_constraint(
        "ck_users_phone_not_blank", "users", "phone IS NULL OR btrim(phone) <> ''", schema="app"
    )
    op.create_check_constraint(
        "ck_users_role", "users", "role IN ('driver', 'owner', 'admin')", schema="app"
    )
    op.create_check_constraint(
        "ck_users_verification_status",
        "users",
        "verification_status IN ('unverified', 'pending', 'verified', 'rejected')",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_users_verification_status", "users", schema="app", type_="check")
    op.drop_constraint("ck_users_role", "users", schema="app", type_="check")
    op.drop_constraint("ck_users_phone_not_blank", "users", schema="app", type_="check")
    op.drop_constraint("ck_users_name_not_blank", "users", schema="app", type_="check")
    op.drop_constraint("ck_users_email_not_blank", "users", schema="app", type_="check")
    # ### end Alembic commands ###
