"""add charger constraints

Revision ID: ad409efaabba
Revises: ffc96748caa8
Create Date: 2026-08-24 01:56:31.386168

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad409efaabba"
down_revision: str | Sequence[str] | None = "ffc96748caa8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_charger_name_not_blank", "chargers", "length(trim(name)) > 0", schema="app"
    )
    op.create_check_constraint(
        "ck_charger_power_positive", "chargers", "power_kw > 0", schema="app"
    )
    op.create_check_constraint(
        "ck_charger_status",
        "chargers",
        "status IN ('available', 'unavailable', 'maintenance', 'offline')",
        schema="app",
    )
    op.create_check_constraint(
        "ck_charger_type_not_blank", "chargers", "length(trim(charger_type)) > 0", schema="app"
    )
    op.create_check_constraint(
        "ck_charger_verification_status",
        "chargers",
        "verification_status IN ('pending', 'verified', 'rejected')",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_charger_verification_status", "chargers", schema="app", type_="check")
    op.drop_constraint("ck_charger_type_not_blank", "chargers", schema="app", type_="check")
    op.drop_constraint("ck_charger_status", "chargers", schema="app", type_="check")
    op.drop_constraint("ck_charger_power_positive", "chargers", schema="app", type_="check")
    op.drop_constraint("ck_charger_name_not_blank", "chargers", schema="app", type_="check")
    # ### end Alembic commands ###
