"""add charger search events

Revision ID: ae1af215d2d1
Revises: aba906602b74
Create Date: 2026-08-24 00:39:40.847005

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae1af215d2d1"
down_revision: str | Sequence[str] | None = "aba906602b74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charger_search_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("vehicle_id", sa.UUID(), nullable=True),
        sa.Column("zone_id", sa.UUID(), nullable=True),
        sa.Column(
            "search_location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("requested_connector_type_id", sa.Integer(), nullable=True),
        sa.Column("requested_power_kw", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("search_radius_km", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("chargers_found", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["requested_connector_type_id"],
            ["app.connector_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["app.vehicles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["app.zones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        "ix_charger_search_events_location",
        "charger_search_events",
        ["search_location"],
        unique=False,
        schema="app",
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_charger_search_events_search_location",
        table_name="charger_search_events",
        schema="app",
        postgresql_using="gist",
    )
    op.drop_table("charger_search_events", schema="app")
    # ### end Alembic commands ###
