"""add amenities tables

Revision ID: ce248beaefd0
Revises: a9f567b2ce78
Create Date: 2026-08-23 01:29:29.382881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce248beaefd0'
down_revision: Union[str, Sequence[str], None] = 'a9f567b2ce78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='app'
    )
    op.create_table('business_amenities',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('amenity_id', sa.UUID(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['app.amenities.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['app.businesses.id'], ),
    sa.PrimaryKeyConstraint('business_id', 'amenity_id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_amenities', schema='app')
    op.drop_table('amenities', schema='app')
    # ### end Alembic commands ###
