"""add business hour exception constraints

Revision ID: dcd4c94fc051
Revises: e3226294218d
Create Date: 2026-08-24 01:45:58.461206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd4c94fc051'
down_revision: Union[str, Sequence[str], None] = 'e3226294218d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_business_hour_exception_time_order', 'business_hour_exceptions', 'end_at > start_at', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_business_hour_exception_time_order', 'business_hour_exceptions', schema='app', type_='check')
    # ### end Alembic commands ###
