"""add charger port constraints

Revision ID: dfb6de608cc4
Revises: ad409efaabba
Create Date: 2026-08-24 01:58:16.435921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb6de608cc4'
down_revision: Union[str, Sequence[str], None] = 'ad409efaabba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_charger_port_number', 'charger_ports', ['charger_id', 'port_number'], schema='app')
    op.create_check_constraint('ck_charger_port_number_positive', 'charger_ports', 'port_number > 0', schema='app')
    op.create_check_constraint('ck_charger_port_power_positive', 'charger_ports', 'max_power_kw > 0', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_charger_port_power_positive', 'charger_ports', schema='app', type_='check')
    op.drop_constraint('ck_charger_port_number_positive', 'charger_ports', schema='app', type_='check')
    op.drop_constraint('uq_charger_port_number', 'charger_ports', schema='app', type_='unique')
    # ### end Alembic commands ###
