"""add charger availability constraints

Revision ID: e3226294218d
Revises: 5ec1e6f17921
Create Date: 2026-08-24 01:43:28.484054

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3226294218d"
down_revision: str | Sequence[str] | None = "5ec1e6f17921"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_charger_availability_schedule",
        "charger_availability",
        ["charger_port_id", "day_of_week", "start_local_time", "end_local_time", "is_unavailable"],
        schema="app",
    )
    op.create_check_constraint(
        "ck_charger_availability_day_of_week",
        "charger_availability",
        "day_of_week BETWEEN 0 AND 6",
        schema="app",
    )
    op.create_check_constraint(
        "ck_charger_availability_time_order",
        "charger_availability",
        "end_local_time > start_local_time",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_charger_availability_time_order", "charger_availability", schema="app", type_="check"
    )
    op.drop_constraint(
        "ck_charger_availability_day_of_week", "charger_availability", schema="app", type_="check"
    )
    op.drop_constraint(
        "uq_charger_availability_schedule", "charger_availability", schema="app", type_="unique"
    )
    # ### end Alembic commands ###
