"""add vehicle and connector tables

Revision ID: e50e189940e8
Revises: fc657bcba35f
Create Date: 2026-08-22 00:22:31.614162

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e50e189940e8"
down_revision: str | Sequence[str] | None = "fc657bcba35f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("current_type", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        schema="app",
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("model_year", sa.Integer(), nullable=True),
        sa.Column("vehicle_class", sa.String(length=30), nullable=False),
        sa.Column("battery_kwh", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("max_ac_kw", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("max_dc_kw", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("estimated_range_km", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("efficiency_wh_per_km", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "battery_kwh IS NULL OR battery_kwh > 0", name="ck_vehicles_battery_positive"
        ),
        sa.CheckConstraint(
            "efficiency_wh_per_km IS NULL OR efficiency_wh_per_km > 0",
            name="ck_vehicles_efficiency_positive",
        ),
        sa.CheckConstraint(
            "estimated_range_km IS NULL OR estimated_range_km >= 0",
            name="ck_vehicles_range_nonnegative",
        ),
        sa.CheckConstraint(
            "max_ac_kw IS NULL OR max_ac_kw >= 0", name="ck_vehicles_max_ac_nonnegative"
        ),
        sa.CheckConstraint(
            "max_dc_kw IS NULL OR max_dc_kw >= 0", name="ck_vehicles_max_dc_nonnegative"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_table(
        "vehicle_connectors",
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("connector_type_id", sa.Integer(), nullable=False),
        sa.Column("is_preferred", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_type_id"],
            ["app.connector_types.id"],
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["app.vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vehicle_id", "connector_type_id"),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_connectors", schema="app")
    op.drop_table("vehicles", schema="app")
    op.drop_table("connector_types", schema="app")
    # ### end Alembic commands ###
