"""add connector type constraints

Revision ID: e6350db55d4a
Revises: dfb6de608cc4
Create Date: 2026-08-24 02:01:37.144444

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6350db55d4a"
down_revision: str | Sequence[str] | None = "dfb6de608cc4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_connector_type_code_not_blank", "connector_types", "btrim(code) <> ''", schema="app"
    )
    op.create_check_constraint(
        "ck_connector_type_display_name_not_blank",
        "connector_types",
        "btrim(display_name) <> ''",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_connector_type_display_name_not_blank", "connector_types", schema="app", type_="check"
    )
    op.drop_constraint(
        "ck_connector_type_code_not_blank", "connector_types", schema="app", type_="check"
    )
    # ### end Alembic commands ###
