"""add charging session constraints

Revision ID: f3fd09c7c33c
Revises: bc0142eb44ea
Create Date: 2026-08-24 01:36:58.424267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fd09c7c33c'
down_revision: Union[str, Sequence[str], None] = 'bc0142eb44ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_charging_sessions_amount_nonnegative', 'charging_sessions', 'amount IS NULL OR amount >= 0', schema='app')
    op.create_check_constraint('ck_charging_sessions_end_after_start', 'charging_sessions', 'ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at', schema='app')
    op.create_check_constraint('ck_charging_sessions_energy_nonnegative', 'charging_sessions', 'energy_kwh IS NULL OR energy_kwh >= 0', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_charging_sessions_energy_nonnegative', 'charging_sessions', schema='app', type_='check')
    op.drop_constraint('ck_charging_sessions_end_after_start', 'charging_sessions', schema='app', type_='check')
    op.drop_constraint('ck_charging_sessions_amount_nonnegative', 'charging_sessions', schema='app', type_='check')
    # ### end Alembic commands ###
