"""add zone constraints

Revision ID: fd6da38b3154
Revises: e6350db55d4a
Create Date: 2026-08-24 02:03:43.560937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6da38b3154'
down_revision: Union[str, Sequence[str], None] = 'e6350db55d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_zone_city_not_blank', 'zones', "btrim(city) <> ''", schema='app')
    op.create_check_constraint('ck_zone_h3_index_not_blank', 'zones', "h3_index IS NULL OR btrim(h3_index) <> ''", schema='app')
    op.create_check_constraint('ck_zone_name_not_blank', 'zones', "btrim(name) <> ''", schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_zone_name_not_blank', 'zones', schema='app', type_='check')
    op.drop_constraint('ck_zone_h3_index_not_blank', 'zones', schema='app', type_='check')
    op.drop_constraint('ck_zone_city_not_blank', 'zones', schema='app', type_='check')
    # ### end Alembic commands ###
