"""add business amenity constraints

Revision ID: ffc96748caa8
Revises: 0cda3d51dc6b
Create Date: 2026-08-24 01:54:27.262450

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffc96748caa8"
down_revision: str | Sequence[str] | None = "0cda3d51dc6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_business_amenity_source_not_blank",
        "business_amenities",
        "length(trim(source)) > 0",
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_business_amenity_source_not_blank", "business_amenities", schema="app", type_="check"
    )
    # ### end Alembic commands ###
