from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


# Shared properties
class PaymentBase(BaseModel):
    amount: float = Field(..., gt=0.0)
    currency: str = Field(default="INR")
    method: Literal["cash", "card", "upi"] = "upi"
    # Enforce strict status values
    status: Literal["pending", "completed", "failed", "refunded"] = "pending"
    provider_order_id: str | None = Field(
        default=None,
        description="Order/session ID generated by the configured payment gateway",
    )
    provider_payment_id: str | None = Field(
        default=None, description="Transaction ID generated upon successful payment"
    )


# Properties for internal creation when a checkout session begins
class PaymentCreate(PaymentBase):
    booking_id: UUID


class PaymentOrderCreate(BaseModel):
    """Public create-order contract; amount is always calculated server-side."""

    booking_id: UUID
    method: Literal["cash", "card", "upi"] = "upi"

    model_config = ConfigDict(extra="forbid")


class PaymentVerifyRequest(BaseModel):
    booking_id: UUID
    provider_order_id: str = Field(..., min_length=1)
    provider_payment_id: str = Field(..., min_length=1)
    provider_signature: str = Field(..., min_length=1)


# Properties for webhook updates (when the gateway confirms payment)
class PaymentUpdate(BaseModel):
    status: str | None = None
    provider_payment_id: str | None = None
    verified_at: datetime | None = None


# Properties returned to the client (e.g., for receipt rendering)
class PaymentResponse(PaymentBase):
    id: UUID
    booking_id: UUID
    verified_at: datetime | None = None
    created_at: datetime
    provider: str | None = None
    checkout_url: str | None = None
    # Returned only from the cash create-order response. It is intentionally
    # absent from booking reads and payment-history responses.
    cash_otp: str | None = None
    cash_otp_expires_at: datetime | None = None

    model_config = ConfigDict(from_attributes=True)


class StripeVerifyRequest(BaseModel):
    booking_id: UUID
    checkout_session_id: str = Field(..., min_length=1)
