from pydantic import BaseModel, Field, ConfigDict
from typing import Literal, Optional
from datetime import datetime


# Shared properties
class PaymentBase(BaseModel):
    amount: float = Field(..., gt=0.0)
    currency: str = Field(default="INR")
    # Enforce strict status values
    status: Literal["pending", "completed", "failed", "refunded"] = "pending"
    provider_order_id: Optional[str] = Field(
        default=None, 
        description="Order ID generated by the payment gateway (e.g., Razorpay Order ID)"
    )
    provider_payment_id: Optional[str] = Field(
        default=None, 
        description="Transaction ID generated upon successful payment"
    )


# Properties for internal creation when a checkout session begins
class PaymentCreate(PaymentBase):
    booking_id: int


# Properties for webhook updates (when the gateway confirms payment)
class PaymentUpdate(BaseModel):
    status: Optional[str] = None
    provider_payment_id: Optional[str] = None
    verified_at: Optional[datetime] = None


# Properties returned to the client (e.g., for receipt rendering)
class PaymentResponse(PaymentBase):
    id: int
    booking_id: int
    verified_at: Optional[datetime] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)